FROM node:21-alpine3.19

WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --network-timeout 600000

COPY . .

RUN yarn run build

RUN yarn migration:run

CMD ["node", "dist/main.js"]

# docker build -f dockerfile.prod -t microservice-gateway .
# docker run -p 3000:3000 microservice-gateway
