FROM node:24.4.1-alpine3.21
WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --frozen-lockfile --network-timeout 600000

COPY . .

RUN yarn run build

CMD ["node", "dist/main.js"]